var store_db = {'0': {'store_id': '16', 'store_name': 'something','store_address':'something','store_city':'dh','store_state':'hp','store_country':'India','store_postalcode':'176025','store_latitude':'32.040249','store_longitude':'75.923096','store_zone_id':''},
'1': {'store_id': '15', 'store_name': 'Oakridge Centre','store_address':'650 W 41st Ave','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V5Z 2M9','store_latitude':'49.231960','store_longitude':'-123.118507','store_zone_id':'0'},
'2': {'store_id': '14', 'store_name': 'Store test','store_address':'1322 West Broadway','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V6H 1H2','store_latitude':'49.263248','store_longitude':'-123.134727','store_zone_id':'0'},
'3': {'store_id': '13', 'store_name': 'Demo Store','store_address':'3823 Lanark Street, Kensington-Cedar Cottage','store_city':' Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':' V5N 3R6','store_latitude':'49.250919','store_longitude':'-123.074944','store_zone_id':''},
'4': {'store_id': '12', 'store_name': 'Callanish Society','store_address':'2902 West Broadway','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V6K 2G8','store_latitude':'49.263870','store_longitude':'-123.170403','store_zone_id':''},
'5': {'store_id': '11', 'store_name': 'Mount Pleasant','store_address':'3081 Main Street
','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V5T 3G6','store_latitude':'49.257702','store_longitude':'-123.101494','store_zone_id':'0'},
'6': {'store_id': '10', 'store_name': 'Mac Simize Computer Svc. Ltd.','store_address':'1496 72nd ave w
','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V6P 3C8','store_latitude':'49.205688','store_longitude':'-123.140259','store_zone_id':'0'},
'7': {'store_id': '9', 'store_name': '8879 Granville St','store_address':' 8879 Granville St','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V6P 5A4','store_latitude':'49.205498','store_longitude':'-123.140686','store_zone_id':'0'},
'8': {'store_id': '8', 'store_name': 'Chevron','store_address':'8884 Granville Street','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V6P 5A8','store_latitude':'49.205307','store_longitude':'-123.140114','store_zone_id':'0'},
'9': {'store_id': '7', 'store_name': 'Iris Beauty Solution','store_address':'1496 W 72nd Ave, Vancouver, BC , Canada','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V6P 3C8','store_latitude':'49.205688','store_longitude':'-123.140259','store_zone_id':''},
'10': {'store_id': '6', 'store_name': 'Demo store','store_address':'New Westminster','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V3M 2H2','store_latitude':'49.190975','store_longitude':'-122.939674','store_zone_id':''},
'11': {'store_id': '5', 'store_name': 'Hastings-Sunrise','store_address':'2822 Yale Street','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V5K 1C6','store_latitude':'49.290512','store_longitude':'-123.046043','store_zone_id':''},
'12': {'store_id': '4', 'store_name': 'Hi-Class Modern Indian Jewellers Jewellery','store_address':'Sunset, Punjabi Market,
6570 Main St
','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V5X 3G9','store_latitude':'49.225060','store_longitude':'-123.101463','store_zone_id':''},
'13': {'store_id': '3', 'store_name': 'Tiffanys Vancouver Bridal','store_address':'3536 E Hastings St','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V5K 2A7','store_latitude':'49.281109','store_longitude':'-123.027229','store_zone_id':''},
'14': {'store_id': '2', 'store_name': 'BC SPCA Thrift Store','store_address':'5239 Victoria Dr, Vancouver','store_city':'Vancouver','store_state':'BC','store_country':'Canada','store_postalcode':'V5P 3V4','store_latitude':'49.237183','store_longitude':'-123.065628','store_zone_id':''},
'15': {'store_id': '1', 'store_name': 'Hudson Bay Vancouver Downtown','store_address':'674 Granville St,  BC V6C 1Z6, Canada','store_city':'Vancouver,','store_state':'BC ','store_country':'Canada','store_postalcode':'V6C 1Z6','store_latitude':'49.283669','store_longitude':'-123.116364','store_zone_id':'0'}};